name: Test on Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    working-directory: E:/Developments/Test/test-automation

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run the program
        run: |
          # cd E:\Developments\Test\test-automation
          # git pull
          npm ci
