name: Test on Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run the program
        run: |
          npm ci
